// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Punters;

namespace Punters.Migrations
{
    [DbContext(typeof(PunterDbContext))]
    [Migration("20181019073354_CreatePunter")]
    partial class CreatePunter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Punters.Bet", b =>
                {
                    b.Property<int>("BetID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MarketID");

                    b.Property<decimal>("Odds");

                    b.Property<decimal>("PotentialPayout");

                    b.Property<int>("PunterID");

                    b.Property<decimal>("Stake");

                    b.HasKey("BetID");

                    b.HasIndex("MarketID");

                    b.HasIndex("PunterID");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("Punters.BetDetails", b =>
                {
                    b.Property<int>("BetID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MarketID");

                    b.Property<string>("MarketName");

                    b.Property<decimal>("Odds");

                    b.Property<decimal>("PotentialPayout");

                    b.Property<int>("PunterID");

                    b.Property<string>("PunterName");

                    b.Property<decimal>("Stake");

                    b.HasKey("BetID");

                    b.ToTable("BetDetails");
                });

            modelBuilder.Entity("Punters.Market", b =>
                {
                    b.Property<int>("MarketID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<decimal>("Odds");

                    b.HasKey("MarketID");

                    b.ToTable("Market");
                });

            modelBuilder.Entity("Punters.Punter", b =>
                {
                    b.Property<int>("PunterID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance");

                    b.Property<string>("PunterName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("PunterID");

                    b.ToTable("Punter");
                });

            modelBuilder.Entity("Punters.Bet", b =>
                {
                    b.HasOne("Punters.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Punters.Punter", "Punter")
                        .WithMany()
                        .HasForeignKey("PunterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
